repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff-check
        args: ["--config", "pyproject.toml", "--fix"]
      - id: ruff-format
        args: ["--config", "pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-orjson>=3.6.2
          - pytest>=8.4.1
          - pytest-asyncio>=1.0.0
          - aiohttp>=3.9.0
          - opentelemetry-api>=1.20.0
          - opentelemetry-exporter-otlp-proto-grpc>=1.20.0
          - opentelemetry-exporter-otlp-proto-http>=1.20.0
          - opentelemetry-sdk>=1.20.0
          - orjson>=3.8.0
          - prometheus-client>=0.20.0
          - structlog>=23.3.0
        args: ["--config-file", "pyproject.toml"]
